version: '3'
services:
  php-fpm:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    volumes:
      - .:/var/www/html
    networks:
      - network

  php:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    volumes:
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    depends_on:
      - php-fpm
    networks:
      - network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    depends_on:
      - php
    environment:
      - php
    networks:
      - network


  mysql:
    container_name: testwork-mysql
    image: mysql:8.0
    restart: on-failure
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    env_file:
      - .env
    ports:
      - "3306:3306"
    networks:
      - network
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_HOST: ${DB_HOST}
      MYSQL_PORT: ${DB_PORT}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
networks:
  network:

volumes:
  mysql-value:
    driver: local
